# Required properties template, the file follows YAML syntax.
svanna:
  # path to folder with SvAnna database and the other required files
  dataDirectory:
  # path to Jannovar transcript database
  jannovarCachePath:

  dataParameters:
    # TAD must be present in at least 25% of the tissues to be included in the analysis
    #tadStabilityThreshold: 0.25
  phenotypeParameters:
    # term similarity measure, choose from {RESNIK_SYMMETRIC, RESNIK_ASYMMETRIC}
    #termSimilarityMeasure: RESNIK_SYMMETRIC
