# SvAnna configuration template. The template follows YAML syntax.
svanna:
  # path to folder with SvAnna database and the other required files.
  dataDirectory:

  #prioritization:
    # term similarity measure, choose from {RESNIK_SYMMETRIC, RESNIK_ASYMMETRIC}
    #termSimilarityMeasure: RESNIK_SYMMETRIC
    # The mode for getting information content of the most informative common ancestors for terms t1, and t2.
    # Choose from {IN_MEMORY, DATABASE}.
    # IN_MEMORY is faster but uses more memory
    # DATABASE is slower but also more memory efficient
    #icMicaMode: DATABASE
    # Number of bases prepended to a transcript and evaluated as a promoter region
    #promoterLength: 2000
    # Set to 0. to score promoter variants as strictly as coding variants, or to 1. to skip
    #promoterFitnessGain: .6