# Required properties template, the file follows YAML syntax.
svanna:
  # path to folder with SvAnna database and the other required files
  dataDirectory:
  # path to Jannovar transcript database
  jannovarCachePath:

